name: lostcard
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0

  font_awesome_flutter: ^10.1.0


  firebase_core: ^1.19.1

  firebase_auth: ^3.4.1

  cloud_firestore: ^3.2.1

  google_sign_in: ^5.4.0

  flutter_facebook_auth: ^4.4.0

  email_auth: ^1.0.0


  carousel_slider: ^4.1.1



  flutter_native_splash: ^2.2.6

  image_picker: ^0.8.5+3

  file_picker: ^5.0.1

  firebase_storage: ^10.3.5

  path: ^1.8.1

  shared_preferences: ^2.0.15










flutter_native_splash:

  color: "#7F1CFE"

  image: assets/images/logo.png






dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf


